// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRYWQbC9EByzZj3S1CyfaCWvXX-G3DDiA',
    appId: '1:715027027369:web:3f0cc2c2e9b8e640aa60b8',
    messagingSenderId: '715027027369',
    projectId: 'child-record-fcda2',
    authDomain: 'child-record-fcda2.firebaseapp.com',
    storageBucket: 'child-record-fcda2.firebasestorage.app',
    measurementId: 'G-NWK2980W1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD68Lkn_nJxep1ltUZQxUYxgBGRWGaGNjE',
    appId: '1:715027027369:android:f27ff17e5f2c506daa60b8',
    messagingSenderId: '715027027369',
    projectId: 'child-record-fcda2',
    storageBucket: 'child-record-fcda2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFt-sH4nMnYsDmpWwF0R8s76sHjD74C48',
    appId: '1:715027027369:ios:e8d10869c75ee956aa60b8',
    messagingSenderId: '715027027369',
    projectId: 'child-record-fcda2',
    storageBucket: 'child-record-fcda2.firebasestorage.app',
    iosClientId: '715027027369-42ipfi8mtq1lovm46l5hacq87n1f8qg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.childRecord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFt-sH4nMnYsDmpWwF0R8s76sHjD74C48',
    appId: '1:715027027369:ios:e8d10869c75ee956aa60b8',
    messagingSenderId: '715027027369',
    projectId: 'child-record-fcda2',
    storageBucket: 'child-record-fcda2.firebasestorage.app',
    iosClientId: '715027027369-42ipfi8mtq1lovm46l5hacq87n1f8qg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.childRecord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRYWQbC9EByzZj3S1CyfaCWvXX-G3DDiA',
    appId: '1:715027027369:web:6de311fdfb3f3694aa60b8',
    messagingSenderId: '715027027369',
    projectId: 'child-record-fcda2',
    authDomain: 'child-record-fcda2.firebaseapp.com',
    storageBucket: 'child-record-fcda2.firebasestorage.app',
    measurementId: 'G-QL1526DMX9',
  );
}
